pipeline {
  agent any
  tools { nodejs 'node18' }  // uses the NodeJS tool you configured

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Install & Test') {
      steps {
        sh 'node -v && npm -v'
        sh 'npm ci || npm install'
        sh 'npm test'
        sh 'echo "Tests passed" > result.txt'
      }
      post {
        always {
          archiveArtifacts artifacts: 'result.txt', fingerprint: true
        }
      }
    }

    // We'll enable Docker build after we wire Docker access for Jenkins
    // stage('Build Docker Image') {
    //   steps { sh 'docker build -t simple-devops-node-app .' }
    // }
  }
}
